name: JSON Schema Linter

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ValidateJSONSchema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install ajv-cli
        run: npm install -g ajv-cli

      - name: Validate JSON Schema structure
        run: ajv compile -s Schema.json --spec=draft2020
